- name: Copy ngrok.service
  copy:
    src: ngrok.service
    dest: /lib/systemd/system/ngrok.service
    owner: root
    group: root
    mode: '0755'
    backup: yes
  register: ngrok_service

- name: Create a directory /opt/ngrok if it does not exist
  file:
    path: /opt/ngrok
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy ngrok.yml
  copy:
    src: ngrok.yml
    dest: /opt/ngrok/
    owner: root
    group: root
    mode: '0755'
    backup: yes
  register: ngrok_yml

- name: Download ngrok
  get_url:
    owner: root
    group: root
    # url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    url: https://monster-local-1-public.s3-eu-west-1.amazonaws.com/ngrok-stable-linux-amd64.tgz
    dest: /opt/
    mode: '0755'

- name: Unarchive ngrok
  become: true
  unarchive:
    src: /opt/ngrok-stable-linux-amd64.tgz
    dest: /opt/ngrok/
  tags:
    - ngrok

- name: Remove file (delete file)
  file:
    path: /opt/ngrok-stable-linux-amd64.tgz
    state: absent

- name: Create log file for ngrok
  file:
    path: /var/log/ngrok.log
    state: touch
    owner: vagrant
    group: vagrant

- name: Disable and stop ngrok service
  service:
    name: ngrok
    enabled: no
    state: stopped
