- name: Update Heroku repo key
  apt_key:
    id: 6DB5542C356545CF
    keyserver: keyserver.ubuntu.com
    state: present

- name: Install python3-pip package
  apt:
    name: python3-pip
    state: present
    update_cache: yes
